---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 010-ServiceAccount-strimzi-cluster-operator.yaml
  - 020-ClusterRole-strimzi-cluster-operator-role.yaml
  - 020-RoleBinding-strimzi-cluster-operator.yaml
  - 021-ClusterRole-strimzi-cluster-operator-role.yaml
  - 021-ClusterRoleBinding-strimzi-cluster-operator.yaml
  - 030-ClusterRole-strimzi-kafka-broker.yaml
  - 030-ClusterRoleBinding-strimzi-cluster-operator-kafka-broker-delegation.yaml
  - 031-ClusterRole-strimzi-entity-operator.yaml
  - 031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml
  - 032-ClusterRole-strimzi-topic-operator.yaml
  - 032-RoleBinding-strimzi-cluster-operator-topic-operator-delegation.yaml
  - 040-Crd-kafka.yaml
  - 041-Crd-kafkaconnect.yaml
  - 042-Crd-kafkaconnects2i.yaml
  - 043-Crd-kafkatopic.yaml
  - 044-Crd-kafkauser.yaml
  - 045-Crd-kafkamirrormaker.yaml
  - 046-Crd-kafkabridge.yaml
  - 047-Crd-kafkaconnector.yaml
  - 048-Crd-kafkamirrormaker2.yaml
  - 049-Crd-kafkarebalance.yaml
  - 050-Deployment-strimzi-cluster-operator.yaml
